### ISSUE TITLE
1602 lcd and Pro Micro

### ISSUE THREAD

**Issue by Croosi** [SaibotFlow/marax-monitor#4]
Hello Saibot,

I have tried to change your code to make it work with a Pro Micro controller and a 1602 display. But as I have no real coding knowledge I think I failed a bit. As far as I can tell I got the Display to show all the data I want, but actually no values from the MaraX. Maybe you can have a look at the code on my page and eventually help me out. However you decide... Thanks :)

Greetings Croosi

**Comment by SaibotFlow** [comment]
Hi Croosi,

I dont know the hardware and I have no experiences with lcds. Sorry for that :/

The first thing I would do: Check the wires. Is everything correct?
Second thing: Try to read data from the MaraX.

I recommend any arduino. Connect your arduino to your laptop and connect the arduino (TX RX) to the Mara X interface.
Open a serial monitor and check if you see the raw data. 
There are many tutorials how to visualize serial data with an arduino.

Another Tip:
Maybe you have a mara with a different interface. I have heard of people who have the same firmware but different data.
Something like that:

Switch Position 0 - +1.06,124,118,094,0000,0,0
Switch Position 1 - C1.06,125,118,094,0000,0,0

You can investigate this, when you visualize the data to a serial monitor.


After that I would check the source code. When you can grab and interpet the data correctly you can implement your frontend :-)
