### ISSUE TITLE
Gnd pin?

### ISSUE THREAD

**Issue by ShuzzDE** [SaibotFlow/marax-monitor#5]
Hi!

Do you have any idea where the GND pin is located on the marax?
I'd like to connect that to the Arduino in order to be sure that the connection is stable...

**Comment by SaibotFlow** [comment]
Hi ShuzzDE,

Im not sure. I assume following assignment - wihtout warranty:

PIN1: VCC 
PIN2: GND
PIN3: RX
PIN4: TX
PIN5: RTS
PIN6: CT

![image](https://user-images.githubusercontent.com/29798226/211355820-dc81cda5-512b-43d1-bde2-b5dbe9a1f53c.png)

PIN direction from right to left.

You could also google for the circuit of the control unit. Usually its the Gicar PL62X

I hope I could help you
