### ISSUE TITLE
Compilation error:Adafruit_GFX.h: No such file or directory

### ISSUE THREAD

**Issue by leonseinpapa** [SaibotFlow/marax-monitor#8]
Hi, this is my error at Arduino 2.2.1

**Comment by SaibotFlow** [comment]
Hi,

I dont rollout external libaries e.g. Adafruit. Normally your IDE should manage this. 
I think you are just missing the libary and you need to install it.

You can do this via: Sketch/Include Libary/ Manage Libary
In the Libary Manager you can install the Adafruit GFX Libary

Here is also a "How to" from Adafruit with Screenshots.

https://learn.adafruit.com/adafruit-gfx-graphics-library/overview

Hope this helps.

**Comment by joekerna** [comment]
Or using commandline

`arduino-cli lib install "Adafruit GFX Library"`
